name: CI-Trabalho-GCES

on: [push]

defaults:
  run:
    working-directory: ./aplicacao

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Build app
        run: docker-compose up -d

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Reset PostgresDB
        run:  docker-compose run railsapp rails db:reset

      - name: Test app
        run: docker-compose run railsapp rspec
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run lint app
        run:  docker-compose run railsapp bash -c "gem install rubocop; rubocop --fail-level F"